name: deploy upyun

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
        cache: 'npm'
    - name: Install Depend
      run: npm install
    - name: Build
      run: npm run build
    - name: Prepare the upload environment
      run: wget --quiet -O- https://github.com/upyun/upx/releases/download/v0.3.6/upx_0.3.6_linux_x86_64.tar.gz | tar -xz
    - name: Deploy Upyun
      run: ./upx login ${{ secrets.BUCKET }} ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} && ./upx sync build/ --delete && ./upx logout

